### ISSUE TITLE
Make PR test subjobs parallelizable

### ISSUE THREAD

**Issue by qstokkink** [Tribler/gumby#309]
Right now the subjobs of the PR tester are in conflict with each other (they try to modify the same working tree).
To fix this I have the tests running sequentially instead of in parallel.

Ideally the subjobs would be completely independent and able to run in parallel though.

**Comment by devos50** [comment]
Pfew, this issue goes back to 2017!

I just looked at this, and after quite some fighting with git refspecs, the issue seems to be that if one job in the multijob pipeline fails, other jobs also fail. But because these other jobs were usually in the middle of a git clone while being aborted, this would lead to vague and unintuitive error messages. I changed the behaviour of the Jenkins jobs to not abort all other jobs in the same pipeline when one fails. 👍

**Comment by devos50** [comment]
Update: there was another error somewhere in the `PR_tests_linux` job, where it was using the same workspace as the upstream parent job. This is the original issue. After trying a few fixes, I unfortunately had no other option than to rebuild the `PR_test_linux` job. It seems to work now 👍
